version: 2.1

workflows:
  test-deploy:
    jobs: 
      - test

jobs:
  test:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run: flutter doctor