version: 2.1

workflows:
  test-deploy:
    jobs: 
      - test

jobs:
  test:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter test 
      - run: flutter -v build apk
